"""
external_apis.py — auto-generated by consolidate_to_folder.py

This file is a concatenation of:
    • jira_prompts.py  (JIRA PROMPT TEMPLATES)
    • JiraClient.py  (JIRA REST API CLIENT)
    • WebSearch.py  (SERPAPI WEB SEARCH)
    • recall_bot.py  (RECALL.AI BOT LIFECYCLE)

Do not edit the section headers below — they mark original file
boundaries for easier debugging.
"""



###########################################################################
# ─── JIRA PROMPT TEMPLATES  (was: jira_prompts.py)
###########################################################################

"""
jira_prompts.py — Jira integration prompts + Azure GPT-4o mini extraction

During meeting: JIRA_INTENT_PROMPT (Groq) classifies what Jira op to run
                JIRA_RESPONSE_PROMPT (Groq) formats Jira data for voice
Post-meeting:   EXTRACTION_PROMPT (Azure GPT-4o mini) extracts action items
"""

import os
import json
import httpx


# ── Prompt for Jira read responses (Groq, during meeting) ────────────────────

JIRA_RESPONSE_PROMPT = """You are Sam, a PM on a live voice call. You just looked up Jira ticket info.

Jira data:
{jira_data}

Rules:
- Speak the info naturally, like telling a coworker.
- If there are MORE than 5 tickets, read the top 5 by priority, then say "Want me to go through the rest?"
- If 5 or fewer, read all of them.
- For each ticket mention: ticket ID, summary, status, and assignee if assigned.
- Don't read raw JSON — summarize it conversationally.
- If a transition was successful, confirm it naturally.
- If a transition failed, explain what moves are available.
- If the ticket is already at the requested status, say so naturally.
- No markdown, no lists — this is voice output.
- Keep it under 30 seconds of speaking time."""


# ── Jira intent classifier (Groq, during meeting) ────────────────────────────

JIRA_INTENT_PROMPT = """You are a Jira intent classifier. Given a user message from a meeting, determine what Jira operation they want.

The Jira project key is: {project_key}

{context_block}User message: "{text}"

Classify into EXACTLY one of these formats:

MY_TICKETS — user wants to see their open/assigned tickets, any tickets in the project, available tickets
SPRINT_STATUS — user wants sprint overview, progress, how many done/in-progress
TICKET:ID — user wants details about a specific ticket (e.g. TICKET:SCRUM-123). For MULTIPLE tickets use comma: TICKET:SCRUM-15,SCRUM-12
TRANSITION:ID:STATUS — user wants to move a ticket to a new status (e.g. TRANSITION:SCRUM-123:Done). Status must be one of: Done, In Progress, To Do
CREATE:SUMMARY — user wants to CREATE a new ticket. Extract a short summary (e.g. CREATE:Code Review for Payment Module)
SEARCH:QUERY — user wants to find tickets by topic/description (e.g. SEARCH:login page bug)

Rules:
- SPOKEN NUMBERS: speech-to-text converts numbers to words. You MUST convert them back.
  "thirty one" = 31, "twenty six" = 26, "twelve" = 12, "forty five" = 45
  "ticket thirty one" = {project_key}-31
  "scrum twenty six" = {project_key}-26
  "move twelve to done" = TRANSITION:{project_key}-12:Done
  
- GARBLED SPEECH: speech-to-text often garbles "move" commands. Look for the INTENT, not exact words.
  "makes from thirty one to done" = TRANSITION:{project_key}-31:Done
  "get it to done" / "move it to done" = look at conversation for which ticket → TRANSITION:ID:Done
  "ticket number twenty six two done" = TRANSITION:{project_key}-26:Done

- CREATE DETECTION: if the user asks to "create", "make", "add", "open", "raise" a ticket/issue/task:
  "create a ticket for code review" = CREATE:Code Review
  "make a ticket for the login bug" = CREATE:Login Bug Fix
  "can you raise a ticket for this" (after discussing chatbot crash) = CREATE:Chatbot Crash
  "create a ticket for this" (after discussing payment API failure) = CREATE:Payment API Failure
  "log this as a ticket" (after discussing deployment issue) = CREATE:Deployment Issue
  IMPORTANT: For "this"/"that"/"it" references, look at recent conversation to identify the actual topic and use that as the summary. NEVER output the literal word "summary" — that's a placeholder, not a real title.

- If user says "define those tickets", "tell me more about those" — look at RECENT CONVERSATION for ticket IDs that were just mentioned and return TICKET:ID,ID
- If unsure, default to MY_TICKETS

Reply with ONLY the classification. Nothing else."""


# ── Prompt for post-meeting extraction (Azure GPT-4o mini) ───────────────────

EXTRACTION_PROMPT = """You are an AI assistant that extracts action items from meeting transcripts.

Analyze the following meeting transcript and extract all actionable items that need Jira tickets.

For each item, output a JSON object with these fields:
- "type": one of "Bug", "Story", "Task"
- "summary": short title (max 80 chars)
- "description": detailed description with context from the meeting
- "priority": "Highest", "High", "Medium", or "Low"
- "labels": list of relevant labels (see rules below)
- "assignee": person's name if someone was explicitly assigned this task, otherwise null

{pending_intents_block}

What counts as an action item:
- Bugs reported (anything broken, crashing, slow, not working)
- Feature requests (new functionality requested)
- Tasks assigned (someone asked to do something)
- Decisions made that need tracking
- Blockers mentioned

Rules:
- Only extract ACTIONABLE items, not general discussion
- ONLY extract items from what HUMAN participants said — IGNORE everything Sam said (lines starting with "Sam:")
- IGNORE any bot errors, connection failures, DNS issues, or technical problems with Sam himself — these are NOT action items
- If the user asked to "create a ticket" but the PENDING CREATION INTENTS section above is empty, then extract the underlying work being requested (e.g. the bug being discussed).
  Example: User says "the chatbot is crashing... create a ticket for this" → extract ONE item about the chatbot crash.
- Include meeting context in descriptions (who said what, why it matters)
- If someone was assigned a task, mention them in the description
- If no action items found, return empty list []
- Be specific in summaries — "Login page crash on Chrome Android" not "Bug fix needed"
- Labels must include "client-feedback" and "session-{meeting_date}" for all items
- For bugs also add "bug" label
- For feature requests add "feature-request" label
- For blockers add "blocker" label
- For urgent/critical items add "critical" label

HANDLING PLURAL REQUESTS:
If a pending intent says something like "create a ticket for each" or "tickets for all those issues",
look at the preceding discussion and create ONE ticket per distinct issue discussed.
Example: if user discussed query optimization, caching, data modeling, and design tweaks, then
said "create a ticket for each", output FOUR tickets — one per topic — not a single generic ticket.

Respond with ONLY a JSON array. No markdown, no explanation, no backticks.

Meeting date: {meeting_date}

Meeting transcript:
{transcript}

Extract action items as JSON array:"""


# ── Prompt for conversation-scoped session summary (Feature 4 Memory) ─────────

SESSION_SUMMARY_PROMPT = """You are summarizing a meeting for long-term memory.
Output STRUCTURED DATA that will be loaded in future meetings with the same group.

Attendees: {attendees}
Meeting date: {meeting_date}

Meeting transcript:
{transcript}

Output a JSON object with EXACTLY these fields:
{{
  "topics": ["..."],
  "decisions": ["..."],
  "commitments": [{{"who": "...", "what": "...", "when": "..."}}],
  "open_items": ["..."],
  "tickets_referenced": [{{"key": "SCRUM-123", "status_at_time": "In Progress"}}],
  "user_concerns": ["..."],
  "summary_text": "2-3 sentence narrative summary"
}}

Rules for accuracy (CRITICAL — this memory feeds future meetings):
- "decisions": ONLY items where the group actually DECIDED something. Options discussed but not decided = NOT a decision.
- "commitments": ONLY explicit commitments with a clear owner. "Someone should look at this" = NOT a commitment.
- "open_items": Things explicitly left unresolved. Not everything discussed.
- "tickets_referenced": Only Jira ticket keys actually mentioned (like SCRUM-162). Include status if mentioned in discussion.
- "user_concerns": What the user seemed worried about or focused on.
- "summary_text": Factual, not speculative. What actually happened.

CRITICAL — DO NOT INVENT:
- Do not add decisions that weren't made
- Do not attribute commitments to people who didn't make them
- Do not infer ticket statuses not mentioned in the transcript
- If the meeting was short/trivial and had nothing substantive, return empty lists
- If something was discussed but unclear, OMIT it rather than guess

If the meeting has no substantive content, return:
{{"topics": [], "decisions": [], "commitments": [], "open_items": [],
  "tickets_referenced": [], "user_concerns": [], "summary_text": "Brief meeting, no notable discussion."}}

Respond with ONLY the JSON object. No markdown, no explanation, no backticks."""


# ── Azure GPT-4o mini client ─────────────────────────────────────────────────

class AzureExtractor:
    """Post-meeting action item extractor using Azure OpenAI GPT-4o mini."""

    def __init__(self):
        self.endpoint   = os.environ.get("AZURE_ENDPOINT", "").strip().rstrip("/")
        self.api_key    = os.environ.get("AZURE_API_KEY", "").strip()
        self.deployment = os.environ.get("AZURE_DEPLOYMENT", "gpt-4o-mini").strip()
        self.api_version = os.environ.get("AZURE_API_VERSION", "2024-02-15-preview").strip()

        if not self.endpoint or not self.api_key:
            print("[Azure] ⚠️  Missing AZURE_ENDPOINT or AZURE_API_KEY — post-meeting extraction disabled")
            self.enabled = False
            return

        self.enabled = True
        self._client = httpx.AsyncClient(timeout=60)
        print(f"[Azure] ✅ Configured: {self.endpoint} (deployment: {self.deployment})")

    async def extract_action_items(self, transcript: str, date_str: str = "",
                                    pending_intents: list | None = None) -> list[dict]:
        """Extract action items from a meeting transcript.

        pending_intents: OPTION C — list of explicit ticket creation intents
        the user requested mid-meeting. These are signals TO CREATE tickets
        (not meta-actions to ignore). Each dict should have:
          - "user_said": the raw utterance
          - "extracted_summary": the classifier's short-hint summary
          - "at_time": timestamp when said

        When pending_intents is non-empty, Azure treats them as explicit user
        requests and creates proper tickets with full context (better titles,
        plural handling, etc.) vs. what the mid-meeting classifier would
        produce from ambiguous speech alone.
        """
        if not self.enabled:
            print("[Azure] ⚠️  Extraction disabled — no Azure credentials")
            return []

        if not transcript or len(transcript.strip()) < 50:
            print("[Azure] ⚠️  Transcript too short — skipping extraction")
            return []

        import time
        if not date_str:
            date_str = time.strftime("%Y-%m-%d", time.gmtime())

        # Build the "pending intents" block for the prompt
        if pending_intents:
            lines = []
            for i, intent in enumerate(pending_intents, 1):
                user_said = intent.get("user_said", "?")
                hint = intent.get("extracted_summary", "?")
                at_time = intent.get("at_time", "?")
                lines.append(
                    f'  {i}. At {at_time}, user said: "{user_said}"\n'
                    f'     (Initial hint: "{hint}")'
                )
            pending_block = (
                "PENDING CREATION INTENTS — the user EXPLICITLY requested these "
                "tickets be created during the meeting. YOU MUST create proper "
                "Jira tickets for each intent below, using the FULL transcript "
                "for context to write accurate titles and descriptions.\n"
                "Do NOT skip any intent. Do NOT treat these as meta-actions.\n\n"
                + "\n".join(lines)
            )
            print(f"[Azure] 📝 Processing {len(pending_intents)} pending creation intent(s)")
        else:
            pending_block = (
                "(No explicit ticket creation intents were recorded during this "
                "meeting. Extract any ACTIONABLE items you find in the transcript "
                "according to the rules below.)"
            )

        prompt = EXTRACTION_PROMPT.format(
            transcript=transcript[:12000],
            meeting_date=date_str,
            pending_intents_block=pending_block,
        )

        url = f"{self.endpoint}/openai/deployments/{self.deployment}/chat/completions?api-version={self.api_version}"

        try:
            print(f"[Azure] 🤖 Extracting action items ({len(transcript)} chars transcript)...")
            t0 = time.time()

            response = None
            for attempt in range(3):
                try:
                    response = await self._client.post(
                        url,
                        headers={"api-key": self.api_key, "Content-Type": "application/json"},
                        json={
                            "messages": [
                                {"role": "system", "content": "You extract action items from meeting transcripts. Respond with JSON only."},
                                {"role": "user", "content": prompt},
                            ],
                            "temperature": 0,
                            "max_tokens": 2000,
                        },
                    )
                    break
                except Exception as net_err:
                    if "getaddrinfo" in str(net_err) or "ConnectError" in str(net_err):
                        if attempt < 2:
                            import asyncio
                            wait = 2.0 * (attempt + 1)
                            print(f"[Azure] ⚠️  DNS error (attempt {attempt+1}/3), retrying in {wait}s...")
                            await asyncio.sleep(wait)
                            continue
                    raise

            if response is None:
                print("[Azure] ❌ All retry attempts failed")
                return []

            if response.status_code != 200:
                print(f"[Azure] ❌ API error {response.status_code}: {response.text[:300]}")
                return []

            data = response.json()
            choices = data.get("choices", [])
            if not choices:
                print(f"[Azure] ❌ No choices in response: {str(data)[:300]}")
                return []
            content = choices[0].get("message", {}).get("content", "")
            if not content:
                print(f"[Azure] ❌ Empty content in response")
                return []

            ms = (time.time() - t0) * 1000
            print(f"[Azure] ⏱ Extraction done: {ms:.0f}ms")
            print(f"[Azure] 📝 Raw response: {content[:200]}")

            content = content.strip()
            if content.startswith("```"):
                content = content.split("\n", 1)[-1]
                content = content.rsplit("```", 1)[0]
            content = content.strip()

            items = json.loads(content)
            if not isinstance(items, list):
                print(f"[Azure] ⚠️  Expected list, got {type(items)}")
                return []

            valid_items = []
            for item in items:
                if isinstance(item, dict) and "summary" in item and "type" in item:
                    item.setdefault("priority", "Medium")
                    item.setdefault("description", item["summary"])
                    item.setdefault("labels", [])
                    if "client-feedback" not in item["labels"]:
                        item["labels"].append("client-feedback")
                    session_label = f"session-{date_str}"
                    if session_label not in item["labels"]:
                        item["labels"].append(session_label)
                    valid_items.append(item)

            print(f"[Azure] ✅ Extracted {len(valid_items)} action item(s)")
            for i, item in enumerate(valid_items):
                print(f"[Azure]   {i+1}. [{item['type']}] {item['summary']} ({item['priority']}) labels={item['labels']}")

            return valid_items

        except json.JSONDecodeError as e:
            print(f"[Azure] ❌ JSON parse failed: {e}")
            print(f"[Azure]   Raw content: {content[:200]}")
            return []
        except Exception as e:
            print(f"[Azure] ❌ Extraction failed: {e}")
            return []

    async def extract_session_summary(self, transcript: str,
                                        attendees: list | None = None,
                                        date_str: str = "") -> dict:
        """Generate a structured summary of a meeting for long-term memory.

        Returns a dict with topics/decisions/commitments/open_items/
        tickets_referenced/user_concerns/summary_text. Empty dict on failure.

        Unlike extract_action_items (which creates Jira tickets), this produces
        memory that will be loaded in future meetings with the same attendee group.
        """
        if not self.enabled:
            print("[Azure] ⚠️  Session summary disabled — no Azure credentials")
            return {}

        if not transcript or len(transcript.strip()) < 50:
            print("[Azure] ⚠️  Transcript too short — skipping summary")
            return {}

        import time
        if not date_str:
            date_str = time.strftime("%Y-%m-%d", time.gmtime())

        attendees_str = ", ".join(attendees) if attendees else "unknown"

        prompt = SESSION_SUMMARY_PROMPT.format(
            transcript=transcript[:12000],
            meeting_date=date_str,
            attendees=attendees_str,
        )

        url = f"{self.endpoint}/openai/deployments/{self.deployment}/chat/completions?api-version={self.api_version}"

        try:
            print(f"[Azure] 🧠 Generating session summary ({len(transcript)} chars, {attendees_str})...")
            t0 = time.time()

            response = None
            for attempt in range(3):
                try:
                    response = await self._client.post(
                        url,
                        headers={"api-key": self.api_key, "Content-Type": "application/json"},
                        json={
                            "messages": [
                                {"role": "system", "content": "You generate structured meeting summaries for AI memory. Respond with JSON only. Never invent facts."},
                                {"role": "user", "content": prompt},
                            ],
                            "temperature": 0.1,  # low temperature for factual accuracy
                            "max_tokens": 1500,
                        },
                    )
                    break
                except Exception as net_err:
                    if "getaddrinfo" in str(net_err) or "ConnectError" in str(net_err):
                        if attempt < 2:
                            import asyncio
                            await asyncio.sleep(1.0 * (attempt + 1))
                            continue
                    raise

            if response is None:
                print("[Azure] ❌ Summary request failed")
                return {}

            elapsed_ms = (time.time() - t0) * 1000
            print(f"[Azure] ⏱ Summary generated: {elapsed_ms:.0f}ms")

            if response.status_code != 200:
                print(f"[Azure] ❌ HTTP {response.status_code}: {response.text[:200]}")
                return {}

            data = response.json()
            content = data["choices"][0]["message"]["content"].strip()

            # Strip markdown fences if present
            if content.startswith("```"):
                lines = content.split("\n")
                content = "\n".join(l for l in lines if not l.strip().startswith("```"))

            summary = json.loads(content)

            # Validate structure
            if not isinstance(summary, dict):
                print(f"[Azure] ❌ Summary not a dict: {type(summary)}")
                return {}

            # Ensure all expected fields exist (empty defaults)
            for field in ["topics", "decisions", "commitments", "open_items",
                          "tickets_referenced", "user_concerns"]:
                if field not in summary or not isinstance(summary[field], list):
                    summary[field] = []

            if "summary_text" not in summary or not isinstance(summary["summary_text"], str):
                summary["summary_text"] = ""

            print(f"[Azure] ✅ Summary: {len(summary['topics'])} topics, "
                  f"{len(summary['decisions'])} decisions, "
                  f"{len(summary['commitments'])} commitments, "
                  f"{len(summary['open_items'])} open items")

            return summary

        except json.JSONDecodeError as e:
            print(f"[Azure] ❌ Summary JSON parse failed: {e}")
            return {}
        except Exception as e:
            print(f"[Azure] ❌ Summary generation failed: {e}")
            return {}

    async def close(self):
        if self.enabled:
            await self._client.aclose()

###########################################################################
# ─── JIRA REST API CLIENT  (was: JiraClient.py)
###########################################################################

"""
JiraClient.py — Jira Cloud REST API wrapper

Features:
  - Read: get ticket, search, my tickets, sprint status, projects, sprints
  - Write: create ticket, add comment, transition (with already-done check)
  - Smart: find related tickets, resolve ticket IDs from speech
  - Resilient: DNS retry (3 attempts), rate limit handling, error classification
"""

import os
import re
import httpx
from typing import Optional


class JiraAuthError(Exception):
    pass

class JiraPermissionError(Exception):
    pass

class JiraNotFoundError(Exception):
    pass

class JiraTransitionError(Exception):
    pass


class JiraClient:
    def __init__(self):
        self.base_url = os.environ.get("JIRA_BASE_URL", "").strip().rstrip("/")
        self.email    = os.environ.get("JIRA_EMAIL", "").strip()
        self.token    = os.environ.get("JIRA_API_TOKEN", "").strip()
        self.project  = os.environ.get("JIRA_DEFAULT_PROJECT", "PROJ").strip()

        if not all([self.base_url, self.email, self.token]):
            print("[Jira] ⚠️  Missing JIRA_BASE_URL, JIRA_EMAIL, or JIRA_API_TOKEN — Jira disabled")
            self.enabled = False
            return

        self.enabled = True
        self._client = httpx.AsyncClient(
            timeout=15,
            auth=(self.email, self.token),
            headers={"Accept": "application/json", "Content-Type": "application/json"},
        )
        print(f"[Jira] ✅ Configured: {self.base_url} (project: {self.project})")

    # ── Core API call with DNS retry ──────────────────────────────────────────

    async def _api(self, method: str, path: str, json_data: dict = None, params: dict = None) -> dict:
        if not self.enabled:
            raise JiraAuthError("Jira is not configured")

        url = f"{self.base_url}/rest/api/3{path}"
        last_err = None

        for attempt in range(3):
            try:
                response = await self._client.request(method, url, json=json_data, params=params)

                if response.status_code == 401:
                    raise JiraAuthError("Invalid Jira credentials — check API token")
                if response.status_code == 403:
                    raise JiraPermissionError("No permission — check API token scope")
                if response.status_code == 404:
                    raise JiraNotFoundError("Not found in Jira")
                if response.status_code == 429:
                    import asyncio
                    print("[Jira] ⚠️  Rate limited — waiting 5s...")
                    await asyncio.sleep(5)
                    response = await self._client.request(method, url, json=json_data, params=params)
                    response.raise_for_status()

                if response.status_code >= 400:
                    print(f"[Jira] API error {response.status_code}: {response.text[:300]}")
                    response.raise_for_status()

                if response.status_code == 204:
                    return {}
                return response.json()

            except (JiraAuthError, JiraPermissionError, JiraNotFoundError, JiraTransitionError):
                raise
            except httpx.TimeoutException:
                raise TimeoutError("Jira is not responding — try again later")
            except Exception as e:
                if isinstance(e, (JiraAuthError, JiraPermissionError, JiraNotFoundError)):
                    raise
                last_err = e
                if "getaddrinfo" in str(e) or "ConnectError" in str(e) or "DNS" in str(e):
                    if attempt < 2:
                        import asyncio
                        wait = 1.0 * (attempt + 1)
                        print(f"[Jira] ⚠️  DNS error (attempt {attempt+1}/3), retrying in {wait}s...")
                        await asyncio.sleep(wait)
                        continue
                print(f"[Jira] Request failed: {e}")
                raise

        raise last_err

    # ── Agile API (boards, sprints) ───────────────────────────────────────────

    async def _agile_api(self, method: str, path: str, params: dict = None, json_data: dict = None) -> dict:
        """Call Jira Agile REST API (different base path)."""
        if not self.enabled:
            raise JiraAuthError("Jira is not configured")
        url = f"{self.base_url}/rest/agile/1.0{path}"
        last_err = None
        for attempt in range(3):
            try:
                response = await self._client.request(method, url, params=params, json=json_data)
                if response.status_code >= 400:
                    if response.status_code == 404:
                        return {"values": []}
                    response.raise_for_status()
                return response.json() if response.text else {}
            except Exception as e:
                last_err = e
                if "getaddrinfo" in str(e) or "ConnectError" in str(e):
                    if attempt < 2:
                        import asyncio
                        await asyncio.sleep(1.0 * (attempt + 1))
                        continue
                raise
        raise last_err

    # ── Connection test ───────────────────────────────────────────────────────

    async def test_connection(self) -> bool:
        if not self.enabled:
            return False
        try:
            data = await self._api("GET", "/myself")
            name = data.get("displayName", "Unknown")
            print(f"[Jira] ✅ Connected as: {name}")
            return True
        except Exception as e:
            print(f"[Jira] ❌ Connection failed: {e}")
            return False

    # ── Project & Sprint discovery ────────────────────────────────────────────

    async def get_projects(self) -> list[dict]:
        """Get all accessible Jira projects."""
        try:
            data = await self._api("GET", "/project", params={"maxResults": 50})
            if isinstance(data, list):
                projects = [{"key": p.get("key", ""), "name": p.get("name", ""), "id": p.get("id", "")} for p in data]
                print(f"[Jira] 📁 Found {len(projects)} project(s)")
                return projects
            return []
        except Exception as e:
            print(f"[Jira] ⚠️  Failed to fetch projects: {e}")
            return []

    async def get_boards(self, project_key: str = None) -> list[dict]:
        """Get Scrum/Kanban boards for a project."""
        try:
            params = {"maxResults": 50}
            if project_key:
                params["projectKeyOrId"] = project_key
            data = await self._agile_api("GET", "/board", params=params)
            boards = [
                {"id": b.get("id", ""), "name": b.get("name", ""), "type": b.get("type", "")}
                for b in data.get("values", [])
            ]
            print(f"[Jira] 📋 Found {len(boards)} board(s)")
            return boards
        except Exception as e:
            print(f"[Jira] ⚠️  Failed to fetch boards: {e}")
            return []

    async def get_sprints(self, board_id: int = None, project_key: str = None) -> list[dict]:
        """Get sprints for a board. If no board_id, finds board from project."""
        try:
            if not board_id and project_key:
                boards = await self.get_boards(project_key)
                if boards:
                    board_id = boards[0]["id"]
            if not board_id:
                boards = await self.get_boards(self.project)
                if boards:
                    board_id = boards[0]["id"]
            if not board_id:
                return []

            data = await self._agile_api("GET", f"/board/{board_id}/sprint", params={"maxResults": 10, "state": "active,future"})
            sprints = [
                {
                    "id": s.get("id", ""),
                    "name": s.get("name", ""),
                    "state": s.get("state", ""),
                    "startDate": s.get("startDate", "")[:10] if s.get("startDate") else "",
                    "endDate": s.get("endDate", "")[:10] if s.get("endDate") else "",
                }
                for s in data.get("values", [])
            ]
            print(f"[Jira] 🏃 Found {len(sprints)} sprint(s) for board {board_id}")
            return sprints
        except Exception as e:
            print(f"[Jira] ⚠️  Failed to fetch sprints: {e}")
            return []

    async def get_active_sprint(self) -> dict | None:
        """Get the currently active sprint. Returns None if no active sprint."""
        try:
            sprints = await self.get_sprints()
            for s in sprints:
                if s.get("state") == "active":
                    return s
            return None
        except Exception:
            return None

    async def move_to_sprint(self, ticket_ids: list[str], sprint_id: int = None) -> bool:
        """Move tickets to a sprint. If no sprint_id, uses active sprint."""
        try:
            if not sprint_id:
                active = await self.get_active_sprint()
                if not active:
                    print("[Jira] ⚠️  No active sprint — skipping sprint assignment")
                    return False
                sprint_id = active["id"]
                sprint_name = active.get("name", sprint_id)
            else:
                sprint_name = sprint_id

            await self._agile_api("POST", f"/sprint/{sprint_id}/issue",
                                   json_data={"issues": ticket_ids})
            for tid in ticket_ids:
                print(f"[Jira] 📋 Assigned {tid} to sprint \"{sprint_name}\"")
            return True
        except Exception as e:
            print(f"[Jira] ⚠️  Sprint assignment failed: {e}")
            return False

    # ── Read operations ───────────────────────────────────────────────────────

    async def get_ticket(self, ticket_id: str) -> dict:
        data = await self._api("GET", f"/issue/{ticket_id}", params={
            "fields": "summary,status,assignee,priority,created,updated,issuetype,description"
        })
        return self._format_ticket(data)

    async def get_my_tickets(self, max_results: int = 10) -> list[dict]:
        jql = f"project = {self.project} AND status != Done ORDER BY assignee ASC, priority DESC, updated DESC"
        return await self.search_jql(jql, max_results)

    async def get_assigned_tickets(self, max_results: int = 10) -> list[dict]:
        jql = f"project = {self.project} AND assignee = currentUser() AND status != Done ORDER BY priority DESC, updated DESC"
        return await self.search_jql(jql, max_results)

    async def get_sprint_tickets(self, max_results: int = 30) -> list[dict]:
        jql = f"project = {self.project} AND sprint in openSprints() ORDER BY status ASC, priority DESC"
        return await self.search_jql(jql, max_results)

    async def get_sprint_status(self) -> dict:
        tickets = await self.get_sprint_tickets(50)
        status_counts = {"Done": 0, "In Progress": 0, "To Do": 0, "Other": 0}
        for t in tickets:
            status = t.get("status", "Other")
            if status in status_counts:
                status_counts[status] += 1
            else:
                status_counts["Other"] += 1
        return {
            "total": len(tickets),
            "done": status_counts["Done"],
            "in_progress": status_counts["In Progress"],
            "to_do": status_counts["To Do"],
            "other": status_counts["Other"],
        }

    async def search_jql(self, jql: str, max_results: int = 10) -> list[dict]:
        data = await self._api("GET", "/search/jql", params={
            "jql": jql,
            "maxResults": max_results,
            "fields": "summary,status,assignee,priority,issuetype,updated,description",
        })
        issues = data.get("issues", [])
        total = data.get("total", len(issues))
        print(f"[Jira] 🔍 JQL returned {len(issues)} issue(s) (total: {total})")
        return [self._format_ticket(i) for i in issues]

    async def count_tickets(self, jql: str) -> int:
        """Get total count matching a JQL query without fetching full results.

        Used for project-size detection to decide pre-load strategy.
        Returns 0 on error so caller can fall back to simple pre-load.
        """
        try:
            data = await self._api("GET", "/search/jql", params={
                "jql": jql,
                "maxResults": 0,  # fetch metadata only, no issues
                "fields": "summary",  # minimal field
            })
            return data.get("total", 0)
        except Exception as e:
            print(f"[Jira] ⚠️  count_tickets failed: {e}")
            return 0

    async def search_text(self, query: str, max_results: int = 5) -> list[dict]:
        jql = f'project = {self.project} AND text ~ "{query}" ORDER BY updated DESC'
        return await self.search_jql(jql, max_results)

    # ── Phase 2+3: autocomplete search + batch fetch ─────────────────────────

    async def search_tickets(self, query: str, max_results: int = 10) -> list[dict]:
        """Lightweight autocomplete search — key + summary + status only.

        Used by the setup UI ticket picker. Matches on summary text and key.
        Returns at most max_results, sorted by recency. Never raises —
        returns empty list on any error (UI should gracefully show "no results").
        """
        if not query or not query.strip():
            return []
        q = query.strip().replace('"', '\\"')
        # Try key-exact match first if it looks like a key (e.g., "SCRUM-244" or "244")
        import re as _re
        key_match = _re.match(r'^([A-Z]+-)?(\d+)$', q, _re.IGNORECASE)
        if key_match:
            key_candidate = key_match.group(0).upper()
            if "-" not in key_candidate:
                key_candidate = f"{self.project}-{key_candidate}"
            try:
                ticket = await self.get_ticket(key_candidate)
                if ticket:
                    return [ticket]
            except Exception:
                pass  # Fall through to text search
        # Text search across summary and description
        jql = f'project = {self.project} AND (summary ~ "{q}" OR text ~ "{q}") ORDER BY updated DESC'
        try:
            return await self.search_jql(jql, max_results=max_results)
        except Exception as e:
            print(f"[Jira] ⚠️  search_tickets failed: {e}")
            return []

    async def get_tickets_batch(self, keys: list[str]) -> list[dict]:
        """Bulk-fetch specific ticket keys (used for pre-fetching setup tickets).

        Returns list of tickets in the order provided (skipping any that fail).
        Uses JQL `key in (...)` which is 1 API call regardless of list size,
        MUCH cheaper than N individual get_ticket() calls.
        """
        # Sanitize and dedupe while preserving order
        seen = set()
        clean_keys = []
        for k in keys:
            if not k:
                continue
            k = k.strip().upper()
            if "-" not in k:
                continue  # invalid format
            if k not in seen:
                seen.add(k)
                clean_keys.append(k)
        if not clean_keys:
            return []
        # JQL: `key in ("X", "Y", "Z")` — single round-trip
        key_list = ', '.join(f'"{k}"' for k in clean_keys)
        jql = f'key in ({key_list})'
        try:
            tickets = await self.search_jql(jql, max_results=min(len(clean_keys), 100))
        except Exception as e:
            print(f"[Jira] ⚠️  get_tickets_batch failed: {e}")
            return []
        # Reorder to match input order
        by_key = {t.get("key"): t for t in tickets}
        return [by_key[k] for k in clean_keys if k in by_key]

    # ── Smart: find related tickets ───────────────────────────────────────────

    async def find_related_tickets(self, summary: str, max_results: int = 3) -> list[dict]:
        """Search for existing tickets similar to a new one being created."""
        words = [w for w in summary.lower().split() if len(w) > 3 and w not in {
            "client", "request", "feature", "issue", "about", "from", "with",
            "that", "this", "there", "their", "they", "have", "been", "should",
        }]
        if not words:
            return []
        query = " ".join(words[:4])
        try:
            results = await self.search_text(query, max_results)
            if results:
                print(f"[Jira] 🔗 Found {len(results)} related ticket(s) for \"{summary[:40]}\"")
            return results
        except Exception as e:
            print(f"[Jira] ⚠️  Related ticket search failed: {e}")
            return []

    # ── Write operations ──────────────────────────────────────────────────────

    async def create_ticket(self, summary: str, issue_type: str = "Task",
                           priority: str = "Medium", description: str = "",
                           labels: list[str] = None, assignee_id: str = None) -> dict:
        fields = {
            "project": {"key": self.project},
            "summary": summary,
            "issuetype": {"name": issue_type},
        }
        if description:
            fields["description"] = {
                "type": "doc", "version": 1,
                "content": [{"type": "paragraph", "content": [{"type": "text", "text": description}]}]
            }
        if priority:
            fields["priority"] = {"name": priority}
        if labels:
            fields["labels"] = labels
        if assignee_id:
            fields["assignee"] = {"accountId": assignee_id}

        data = await self._api("POST", "/issue", json_data={"fields": fields})
        ticket_key = data.get("key", "unknown")
        print(f"[Jira] ✅ Created: {ticket_key} — {summary}")
        return {"key": ticket_key, "id": data.get("id"), "summary": summary}

    async def _get_subtask_type_name(self) -> str:
        """Discover the project's subtask issue type name (varies by configuration)."""
        if hasattr(self, '_subtask_type_name') and self._subtask_type_name:
            return self._subtask_type_name
        try:
            data = await self._api("GET", "/issuetype")
            if isinstance(data, list):
                for it in data:
                    if it.get("subtask") is True:
                        name = it.get("name", "")
                        print(f"[Jira] 🔍 Discovered subtask type: \"{name}\"")
                        self._subtask_type_name = name
                        return name
            print(f"[Jira] ⚠️  No subtask type found in project, available types: {[it.get('name') for it in data if isinstance(data, list)]}")
        except Exception as e:
            print(f"[Jira] ⚠️  Failed to discover subtask type: {e}")
        self._subtask_type_name = "Sub-task"  # fallback
        return "Sub-task"

    async def create_subtask(self, parent_key: str, summary: str,
                              description: str = "", priority: str = "Medium",
                              labels: list[str] = None) -> dict:
        """Create a subtask under a parent ticket.
        Auto-discovers the project's subtask issue type name.
        If parent is already a subtask, creates under grandparent instead."""
        # Check if parent is itself a subtask (can't nest subtasks)
        try:
            parent_data = await self._api("GET", f"/issue/{parent_key}", params={
                "fields": "issuetype,parent"
            })
            parent_fields = parent_data.get("fields", {})
            parent_type = parent_fields.get("issuetype", {})
            if parent_type.get("subtask") is True:
                grandparent = parent_fields.get("parent", {})
                gp_key = grandparent.get("key", "")
                if gp_key:
                    print(f"[Jira] 🔄 {parent_key} is a subtask — creating under grandparent {gp_key} instead")
                    parent_key = gp_key
                else:
                    print(f"[Jira] ⚠️  {parent_key} is a subtask with no parent — creating standalone ticket")
                    return await self.create_ticket(summary=summary, issue_type="Task",
                                                     priority=priority, description=description, labels=labels)
        except Exception as e:
            print(f"[Jira] ⚠️  Parent check failed for {parent_key}: {e}")

        # Discover the correct subtask type name for this project
        subtask_type = await self._get_subtask_type_name()

        # Build ADF description with proper formatting
        desc_paragraphs = []
        for line in description.split("\n"):
            line = line.strip()
            if not line:
                continue
            desc_paragraphs.append({
                "type": "paragraph",
                "content": [{"type": "text", "text": line}]
            })
        if not desc_paragraphs:
            desc_paragraphs = [{"type": "paragraph", "content": [{"type": "text", "text": description or "Standup update"}]}]

        fields = {
            "project": {"key": self.project},
            "parent": {"key": parent_key},
            "summary": summary,
            "issuetype": {"name": subtask_type},
            "description": {
                "type": "doc", "version": 1,
                "content": desc_paragraphs,
            },
        }
        if priority:
            fields["priority"] = {"name": priority}
        if labels:
            fields["labels"] = labels

        try:
            data = await self._api("POST", "/issue", json_data={"fields": fields})
            ticket_key = data.get("key", "unknown")
            print(f"[Jira] ✅ Subtask created: {ticket_key} under {parent_key} — {summary}")
            return {"key": ticket_key, "id": data.get("id"), "parent": parent_key, "summary": summary}
        except Exception as e:
            print(f"[Jira] ❌ Subtask creation failed (type: \"{subtask_type}\"): {e}")
            raise

    async def add_comment(self, ticket_id: str, comment: str) -> dict:
        body = {
            "body": {
                "type": "doc", "version": 1,
                "content": [{"type": "paragraph", "content": [{"type": "text", "text": comment}]}]
            }
        }
        data = await self._api("POST", f"/issue/{ticket_id}/comment", json_data=body)
        print(f"[Jira] ✅ Comment added to {ticket_id}")
        return data

    async def get_transitions(self, ticket_id: str) -> list[dict]:
        data = await self._api("GET", f"/issue/{ticket_id}/transitions")
        return data.get("transitions", [])

    async def transition_ticket(self, ticket_id: str, target_status: str) -> dict:
        ticket = await self.get_ticket(ticket_id)
        current_status = ticket.get("status", "Unknown")

        if current_status.lower() == target_status.lower():
            return {"ticket": ticket_id, "already_at": current_status, "action": "already_done"}

        transitions = await self.get_transitions(ticket_id)
        target_lower = target_status.lower()
        match = None
        for t in transitions:
            if t["name"].lower() == target_lower or t["to"]["name"].lower() == target_lower:
                match = t
                break

        if not match:
            available_names = [f"{t['to']['name']}" for t in transitions]
            raise JiraTransitionError(
                f"Can't move {ticket_id} from '{current_status}' to '{target_status}'. "
                f"Available moves: {', '.join(available_names) if available_names else 'none'}"
            )

        await self._api("POST", f"/issue/{ticket_id}/transitions", json_data={"transition": {"id": match["id"]}})
        new_status = match["to"]["name"]
        print(f"[Jira] ✅ {ticket_id} → {new_status}")
        return {"ticket": ticket_id, "new_status": new_status, "action": "transitioned"}

    # ── Ticket ID resolver ────────────────────────────────────────────────────

    def resolve_ticket_id(self, spoken_text: str) -> Optional[str]:
        text = spoken_text.strip()
        match = re.search(r'\b([A-Z]+-\d+)\b', text)
        if match:
            return match.group(1)
        match = re.search(r'\b(\w+)\s+(\d+)\b', text, re.IGNORECASE)
        if match:
            prefix = match.group(1).upper()
            number = match.group(2)
            if prefix in ("PROJ", "PROJECT", "TICKET", "ISSUE", "TASK", "BUG"):
                return f"{self.project}-{number}"
            if len(prefix) <= 6 and prefix.isalpha():
                return f"{prefix}-{number}"
        match = re.search(r'\b(\d+)\b', text)
        if match:
            return f"{self.project}-{match.group(1)}"
        digit_words = {"zero":"0","one":"1","two":"2","three":"3","four":"4","five":"5","six":"6","seven":"7","eight":"8","nine":"9"}
        words = text.lower().split()
        consecutive_digits = []
        current_run = []
        for w in words:
            if w in digit_words:
                current_run.append(digit_words[w])
            else:
                if len(current_run) >= 2:
                    consecutive_digits = current_run
                current_run = []
        if len(current_run) >= 2:
            consecutive_digits = current_run
        if consecutive_digits:
            return f"{self.project}-{''.join(consecutive_digits)}"
        return None

    # ── Helpers ───────────────────────────────────────────────────────────────

    def _format_ticket(self, issue: dict) -> dict:
        if not issue:
            return {"key": "?", "summary": "Unknown", "status": "Unknown", "priority": "Unknown",
                    "type": "Unknown", "assignee": "Unassigned", "updated": "", "description": ""}
        fields = issue.get("fields") or {}
        assignee = fields.get("assignee")
        status = fields.get("status") or {}
        priority = fields.get("priority") or {}
        issuetype = fields.get("issuetype") or {}
        # Extract description text (ADF or plain text)
        desc_raw = fields.get("description") or ""
        if isinstance(desc_raw, dict):
            # Atlassian Document Format — extract text content
            desc_parts = []
            for block in desc_raw.get("content", []):
                for item in block.get("content", []):
                    if item.get("type") == "text":
                        desc_parts.append(item.get("text", ""))
            desc_raw = " ".join(desc_parts)
        desc_text = str(desc_raw)[:200]  # Truncate to 200 chars
        return {
            "key": issue.get("key", ""),
            "summary": fields.get("summary", ""),
            "status": status.get("name", "Unknown"),
            "priority": priority.get("name", "Medium"),
            "type": issuetype.get("name", "Task"),
            "assignee": assignee.get("displayName", "Unassigned") if assignee else "Unassigned",
            "updated": (fields.get("updated") or "")[:10],
            "description": desc_text,
        }

    async def search_user(self, display_name: str) -> Optional[str]:
        try:
            data = await self._api("GET", "/user/search", params={"query": display_name, "maxResults": 1})
            if data and isinstance(data, list) and len(data) > 0:
                account_id = data[0].get("accountId")
                found_name = data[0].get("displayName", "?")
                print(f"[Jira] 👤 User lookup: \"{display_name}\" → {found_name} ({account_id})")
                return account_id
            print(f"[Jira] 👤 User not found: \"{display_name}\"")
            return None
        except Exception as e:
            print(f"[Jira] ⚠️  User search failed for \"{display_name}\": {e}")
            return None

    async def close(self):
        if self.enabled:
            await self._client.aclose()

###########################################################################
# ─── SERPAPI WEB SEARCH  (was: WebSearch.py)
###########################################################################

"""
WebSearch.py — SerpAPI Google Search
Query conversion handled by Agent.py (LLM-based).
Rotates between 2 API keys to avoid rate limits.
"""

import os
import re
import httpx
from typing import Optional


class WebSearch:
    def __init__(self):
        self._keys = []
        # Load SERPAPI_KEY_1 through SERPAPI_KEY_17 (only those set)
        for i in range(1, 18):
            k = os.environ.get(f"SERPAPI_KEY_{i}", "").strip().strip('"\'')
            if k:
                self._keys.append(k)
        # Backwards compatibility: also accept SERPAPI_KEY (unnumbered)
        k_plain = os.environ.get("SERPAPI_KEY", "").strip().strip('"\'')
        if k_plain and k_plain not in self._keys:
            self._keys.append(k_plain)
        if not self._keys:
            print("[WebSearch] ⚠️  No SERPAPI keys — web search disabled")
        else:
            first = self._keys[0]
            print(f"[WebSearch] {len(self._keys)} key(s) loaded (key1: {first[:8]}...)")
        self._key_index = 0
        self._client = httpx.AsyncClient(timeout=20.0)

    def _next_key(self) -> str:
        key = self._keys[self._key_index % len(self._keys)]
        self._key_index += 1
        return key

    def _trim_query(self, query: str, max_words: int = 20) -> str:
        """Clean up query — strip tags, prefixes, cap length."""
        clean = re.sub(r'\[LANG:\w+\]\s*', '', query).strip()
        for prefix in ["sam,", "sam ", "hey sam,", "hey sam ",
                        "can you tell me", "could you tell me",
                        "please tell me", "do you know",
                        "i want to know", "tell me"]:
            if clean.lower().startswith(prefix):
                clean = clean[len(prefix):].strip().lstrip(",. ")
        words = clean.split()
        return " ".join(words[:max_words])

    async def search(self, query: str) -> Optional[str]:
        """Search via SerpAPI Google AI Mode with geo grounding.

        SWITCHED FROM engine='google' TO engine='google_ai_mode' so Sam gets
        Google's pre-synthesized AI answer for in-meeting research questions.
        Adds geo grounding (gl/hl/location, India defaults) so AI Mode treats
        queries as locally-rooted and is more likely to synthesize answers
        rather than just returning citations.

        Response handling (in priority order):
          1. reconstructed_markdown — full prose synthesis (best case)
          2. text_blocks — paragraph snippets (assemble into prose)
          3. references-only fallback — retry once if first attempt was empty;
             after retry, stitch top citation snippets if still no synthesis

        Configurable via env: SERPAPI_GL, SERPAPI_HL, SERPAPI_LOCATION.

        Returns voice-ready text (up to 800 chars) or None on hard failure.
        """
        if not self._keys:
            return None

        import time as _t
        import os as _os
        t_start = _t.time()

        trimmed = self._trim_query(query)

        # Geo grounding params — same defaults as Know About Them flow.
        # Override per-environment with env vars if you serve different regions.
        gl_param = (_os.environ.get("SERPAPI_GL") or "in").strip()
        hl_param = (_os.environ.get("SERPAPI_HL") or "en").strip()
        location_param = (_os.environ.get("SERPAPI_LOCATION") or "India").strip()

        print(f"[WebSearch] SerpAPI AI Mode query: \"{trimmed}\"")
        print(f"[WebSearch] Geo: gl={gl_param}, hl={hl_param}, location={location_param}")
        print(f"[WebSearch] ⏱ [STEP 1] prep done: {(_t.time()-t_start)*1000:.0f}ms")

        # Try up to 2 attempts because AI Mode is non-deterministic — same query
        # can return synthesis or just citations depending on Google session.
        last_references: list = []
        last_data: dict = {}

        for attempt_num in range(1, 3):  # 1, 2 (max 2 attempts = 1 retry)
            api_key = self._next_key()
            print(f"[WebSearch] Attempt {attempt_num} (key #{self._key_index})")

            try:
                # STEP 2: HTTP round-trip
                t_http = _t.time()
                resp = await self._client.get(
                    "https://serpapi.com/search.json",
                    params={
                        "engine": "google_ai_mode",
                        "q": trimmed,
                        "api_key": api_key,
                        "gl": gl_param,
                        "hl": hl_param,
                        "location": location_param,
                    },
                )
                t_http_done = _t.time()
                content_len = len(resp.content) if resp.content else 0
                print(f"[WebSearch] ⏱ [STEP 2] HTTP round-trip: "
                      f"{(t_http_done-t_http)*1000:.0f}ms "
                      f"(status={resp.status_code}, {content_len} bytes)")

                if resp.status_code != 200:
                    print(f"[WebSearch] Attempt {attempt_num}: HTTP "
                          f"{resp.status_code}: {resp.text[:200]}")
                    continue  # retry

                # STEP 3: parse JSON
                t_parse = _t.time()
                data = resp.json()
                last_data = data
                print(f"[WebSearch] ⏱ [STEP 3] JSON parse: "
                      f"{(_t.time()-t_parse)*1000:.0f}ms")

                # Diagnostic: which top-level fields came back?
                top_keys = [
                    k for k in data.keys()
                    if k not in ("search_metadata", "search_parameters")
                ]
                print(f"[WebSearch] Attempt {attempt_num}: fields={top_keys}")

                # STEP 4: extract synthesized answer in priority order
                t_extract = _t.time()

                # 1. reconstructed_markdown — preferred (full prose answer)
                recon = (data.get("reconstructed_markdown", "") or "").strip()
                if recon:
                    cleaned = self._strip_markdown_for_voice(recon)[:800]
                    print(f"[WebSearch] ⏱ [STEP 4] field extract "
                          f"(reconstructed_markdown): {(_t.time()-t_extract)*1000:.0f}ms")
                    print(f"[WebSearch] ✅ AI Mode synthesized "
                          f"({len(cleaned)} chars via markdown)")
                    print(f"[WebSearch] ⏱ [TOTAL] search(): "
                          f"{(_t.time()-t_start)*1000:.0f}ms (attempt {attempt_num})")
                    return cleaned

                # 2. text_blocks — assemble paragraph snippets
                text_blocks = data.get("text_blocks", []) or []
                if text_blocks:
                    parts = []
                    for b in text_blocks:
                        if not isinstance(b, dict):
                            continue
                        snippet = (b.get("snippet") or b.get("text") or "").strip()
                        if snippet:
                            parts.append(snippet)
                        for it in (b.get("list") or []):
                            if isinstance(it, dict):
                                it_snip = (it.get("snippet") or it.get("text") or "").strip()
                                if it_snip:
                                    parts.append(it_snip)
                    if parts:
                        combined = self._strip_markdown_for_voice(" ".join(parts))[:800]
                        print(f"[WebSearch] ⏱ [STEP 4] field extract "
                              f"(text_blocks): {(_t.time()-t_extract)*1000:.0f}ms")
                        print(f"[WebSearch] ✅ AI Mode synthesized "
                              f"({len(combined)} chars via text_blocks)")
                        print(f"[WebSearch] ⏱ [TOTAL] search(): "
                              f"{(_t.time()-t_start)*1000:.0f}ms (attempt {attempt_num})")
                        return combined

                # 3. References-only response — capture for fallback after retries
                last_references = data.get("references", []) or []
                print(f"[WebSearch] Attempt {attempt_num}: only references "
                      f"({len(last_references)} citations) — will retry if attempts remain")

            except httpx.TimeoutException:
                print(f"[WebSearch] Attempt {attempt_num}: TIMEOUT on \"{trimmed}\"")
                continue
            except Exception as e:
                print(f"[WebSearch] Attempt {attempt_num}: Error {type(e).__name__}: {e}")
                continue

        # All attempts exhausted without synthesis. Fall back to stitching the
        # citation snippets from the last response. This is a downgrade —
        # raw citation excerpts, not synthesized prose — but it's grounded in
        # real Google sources, which is better than returning nothing.
        if last_references:
            snippet_parts = []
            for r in last_references[:5]:  # cap at top 5 to keep latency low
                if not isinstance(r, dict):
                    continue
                sn = (r.get("snippet") or "").strip()
                if sn:
                    sn = re.sub(r"\s+", " ", sn).strip()
                    snippet_parts.append(sn)

            # Dedupe near-identical leading text
            seen = set()
            unique = []
            for s in snippet_parts:
                key = s[:60].lower()
                if key not in seen:
                    seen.add(key)
                    unique.append(s)

            if unique:
                combined = " ".join(unique)[:800]
                print(f"[WebSearch] ⚠️  Fallback: stitched {len(unique)} citation "
                      f"snippets ({len(combined)} chars) — no synthesis after retries")
                print(f"[WebSearch] ⏱ [TOTAL] search(): "
                      f"{(_t.time()-t_start)*1000:.0f}ms (references-fallback)")
                return combined

        # Truly nothing usable — return None so caller can fall back to Azure
        print(f"[WebSearch] ❌ No usable content after all attempts")
        print(f"[WebSearch] ⏱ [TOTAL] search() — empty: "
              f"{(_t.time()-t_start)*1000:.0f}ms")
        return None

    @staticmethod
    def _strip_markdown_for_voice(text: str) -> str:
        """Strip markdown formatting from AI Mode output so TTS sounds natural.

        AI Mode's reconstructed_markdown often contains [text](url) inline
        links, ### headers, * bullets, and \\(escaped\\) chars. Voice users
        don't want to hear "open square bracket text close square bracket
        open paren U R L" — strip it all to plain prose.

        Lighter-weight version of server.py's _clean_profile_markdown
        (which is more aggressive). For in-meeting use we just want clean
        readable prose with no markdown noise.
        """
        if not text:
            return ""
        s = text

        # Drop trailing References/Sources/Citations blocks
        s = re.sub(
            r"\s*#{1,6}\s*(References|Sources|Citations)\b.*$",
            "",
            s,
            flags=re.IGNORECASE | re.DOTALL,
        )

        # Convert inline markdown links [text](url) → "text"
        s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", s)

        # Drop bare citation markers [0], [12], [^3]
        s = re.sub(r"\[\^?\d+\]", "", s)

        # Strip headers, bold, italic markers
        s = re.sub(r"^\s*#{1,6}\s+", "", s, flags=re.MULTILINE)
        s = re.sub(r"\*\*([^*]+)\*\*", r"\1", s)
        s = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"\1", s)

        # Strip mid-line headers and bullets (single-line markdown)
        s = re.sub(r"\s*#{1,6}\s+", " ", s)
        s = re.sub(r"(?:^|\s)[-*•]\s+", " ", s)

        # Unescape common backslash-escaped punctuation
        s = s.replace("\\(", "(").replace("\\)", ")")
        s = s.replace("\\-", "-").replace("\\+", "+")
        s = s.replace("\\&", "&").replace("\\.", ".")
        s = s.replace("\\,", ",").replace("\\:", ":")

        # Collapse whitespace
        s = re.sub(r"\s+", " ", s).strip()
        return s

    async def search_raw(self, query: str, max_length: int = 2000,
                          use_references_fallback: bool = False) -> Optional[str]:
        """Search via SerpAPI Google AI Mode engine — for rich persona-based queries.

        IMPORTANT: Uses engine='google_ai_mode' (NOT 'google'). These are
        different SerpAPI products:
          - engine='google' → regular Google Search (returns organic + AI Overview)
          - engine='google_ai_mode' → Google AI Mode (returns AI-generated answer)

        Response structure for google_ai_mode:
          - text_blocks: list of structured blocks (paragraphs, lists)
          - reconstructed_markdown: complete markdown answer (top-level field)
          - references: citation links (each with title, snippet, source, link)
          - search_metadata.status: 'Success' or 'Error'

        Returns the answer text (up to 1500 chars) or None on failure.

        use_references_fallback (default False):
          When True, if neither reconstructed_markdown nor text_blocks come
          back from Google, stitch the reference snippets into prose as a
          last resort. This is a DOWNGRADE — references are raw citations,
          not synthesized answers — so callers must opt in. Useful for
          niche-entity queries (small companies, individual professionals)
          where Google sometimes returns only citations without synthesis.
          Default False preserves existing behavior for all current callers.

        DEBUG MODE: logs full query + response + saves raw JSON to disk.
        Set SERPAPI_DEBUG=0 in env to disable JSON dumps.
        """
        if not self._keys:
            return None

        # Cap length to avoid query limits
        if len(query) > max_length:
            print(f"[WebSearch] ⚠️  Query truncated: {len(query)} → {max_length} chars")
            query = query[:max_length]

        api_key = self._next_key()
        debug_enabled = os.environ.get("SERPAPI_DEBUG", "1") != "0"

        # ── DEBUG: Log full query ──
        print(f"[WebSearch] ═══════════════════════════════════════════════════════")
        print(f"[WebSearch] Google AI Mode query: {len(query)} chars (key #{self._key_index})")
        print(f"[WebSearch] ── Full query ──")
        for line in query.split("\n"):
            print(f"[WebSearch] │ {line}")
        print(f"[WebSearch] ── End of query ──")

        try:
            resp = await self._client.get(
                "https://serpapi.com/search.json",
                params={
                    "engine": "google_ai_mode",  # Google AI Mode engine
                    "q": query,
                    "api_key": api_key,
                    # Location/language params help AI Mode ground properly.
                    # Without these, SerpAPI's US servers can hit a variant of
                    # AI Mode that skips grounding and just makes things up.
                    # "in" = India (matches AnavClouds' web presence).
                    "gl": os.environ.get("SERPAPI_GL", "in"),
                    "hl": os.environ.get("SERPAPI_HL", "en"),
                    "location": os.environ.get("SERPAPI_LOCATION", "India"),
                },
            )
            if resp.status_code != 200:
                print(f"[WebSearch] ❌ HTTP {resp.status_code}: {resp.text[:300]}")
                print(f"[WebSearch] ═══════════════════════════════════════════════════════")
                return None
            data = resp.json()

            # ── DEBUG: Save raw response ──
            if debug_enabled:
                try:
                    import json as _json
                    import time as _t
                    timestamp = _t.strftime("%Y%m%d-%H%M%S")
                    debug_dir = "serpapi_debug"
                    os.makedirs(debug_dir, exist_ok=True)
                    debug_file = os.path.join(debug_dir, f"aimode_{timestamp}.json")
                    with open(debug_file, "w", encoding="utf-8") as f:
                        _json.dump({
                            "query": query,
                            "response": data,
                        }, f, indent=2, ensure_ascii=False)
                    print(f"[WebSearch] 💾 Debug saved: {debug_file}")
                except Exception as _e:
                    print(f"[WebSearch] ⚠️  Debug save failed: {_e}")

            # Check search status
            meta = data.get("search_metadata", {})
            status = meta.get("status", "?")
            if status != "Success":
                err = data.get("error") or meta.get("error", "")
                print(f"[WebSearch] ❌ AI Mode status: {status}, error: {err[:200]}")
                print(f"[WebSearch] ═══════════════════════════════════════════════════════")
                return None

            # ── DEBUG: Log which fields came back ──
            top_keys = [k for k in data.keys() if k not in ("search_metadata", "search_parameters")]
            print(f"[WebSearch] Response top-level fields: {top_keys}")

            # ── Grounding signal (informational only, not gating) ──
            # Earlier versions rejected responses missing 'references' as ungrounded.
            # Removed because it threw away factually correct answers (e.g. AnavClouds
            # office location) where AI Mode just didn't surface references in the
            # response format. We log the signal but trust the response either way.
            references = data.get("references", [])
            if isinstance(references, list) and len(references) > 0:
                print(f"[WebSearch] ℹ️  Response has {len(references)} reference(s) (grounded)")
            else:
                print(f"[WebSearch] ℹ️  Response has no references field (grounding status unknown)")

            # Strategy 1: reconstructed_markdown (preferred — complete answer)
            reconstructed = data.get("reconstructed_markdown", "") or ""
            if reconstructed and reconstructed.strip():
                print(f"[WebSearch] ✅ reconstructed_markdown ({len(reconstructed)} chars)")
                print(f"[WebSearch] ── Content (first 300 chars) ──")
                print(f"[WebSearch] {reconstructed[:300]}")
                print(f"[WebSearch] ═══════════════════════════════════════════════════════")
                return reconstructed[:1500]

            # Strategy 2: text_blocks (fallback if reconstructed_markdown missing)
            text_blocks = data.get("text_blocks", [])
            if text_blocks:
                print(f"[WebSearch] text_blocks count: {len(text_blocks)}")
                parts = []
                for b in text_blocks:
                    snippet = b.get("snippet") or b.get("text") or ""
                    if snippet:
                        parts.append(snippet)
                    for item in b.get("list", []):
                        item_text = item.get("snippet") or item.get("text") or ""
                        if item_text:
                            parts.append(item_text)
                if parts:
                    combined = " ".join(parts)
                    print(f"[WebSearch] ✅ text_blocks assembled ({len(combined)} chars)")
                    print(f"[WebSearch] ── Content (first 300 chars) ──")
                    print(f"[WebSearch] {combined[:300]}")
                    print(f"[WebSearch] ═══════════════════════════════════════════════════════")
                    return combined[:1500]
                else:
                    print(f"[WebSearch] ⚠️  text_blocks exist but no usable text")

            # Strategy 3 (opt-in): stitch reference snippets when nothing else
            # came back. This is a DOWNGRADE — references are raw source
            # citations, not a synthesized answer — so it's gated behind the
            # use_references_fallback flag. Useful for niche-entity queries
            # where Google returns only citations without synthesis (e.g.
            # small/private companies, individual professionals).
            if use_references_fallback and isinstance(references, list) and references:
                snippet_parts = []
                for r in references:
                    if not isinstance(r, dict):
                        continue
                    sn = (r.get("snippet") or "").strip()
                    if sn:
                        # Trim leading "Date —" prefixes and dedupe whitespace
                        sn = re.sub(r"\s+", " ", sn).strip()
                        snippet_parts.append(sn)
                if snippet_parts:
                    # Dedupe near-identical snippets (citations often repeat)
                    seen_lower = set()
                    unique = []
                    for s in snippet_parts:
                        key = s[:80].lower()
                        if key not in seen_lower:
                            seen_lower.add(key)
                            unique.append(s)
                    combined = " ".join(unique)
                    print(f"[WebSearch] ✅ references-fallback assembled "
                          f"({len(unique)} unique snippets, {len(combined)} chars)")
                    print(f"[WebSearch] ── Content (first 300 chars) ──")
                    print(f"[WebSearch] {combined[:300]}")
                    print(f"[WebSearch] ═══════════════════════════════════════════════════════")
                    return combined[:1500]
                else:
                    print(f"[WebSearch] ⚠️  references exist but no usable snippets")

            # Neither strategy worked
            print(f"[WebSearch] ❌ No usable content in AI Mode response → caller falls back to Azure")
            print(f"[WebSearch] ═══════════════════════════════════════════════════════")
            return None

        except httpx.TimeoutException:
            print(f"[WebSearch] ❌ AI Mode TIMEOUT")
            print(f"[WebSearch] ═══════════════════════════════════════════════════════")
            return None
        except Exception as e:
            print(f"[WebSearch] ❌ AI Mode error: {type(e).__name__}: {e}")
            print(f"[WebSearch] ═══════════════════════════════════════════════════════")
            return None
            return None

    async def close(self):
        await self._client.aclose()

###########################################################################
# ─── RECALL.AI BOT LIFECYCLE  (was: recall_bot.py)
###########################################################################

"""
recall_bot.py — Recall.ai bot with Output Media + configurable STT

Audio delivery: Output Media (webpage streams PCM via AudioWorklet)
Fallback: automatic_audio_output (MP3 injection) if output_media disabled

STT Configuration:
    Standup mode:
        Uses Recall.ai's own STT (AssemblyAI or Deepgram depending on
        USE_ASSEMBLYAI). Audio flows from Recall → AssemblyAI/Deepgram →
        transcript.data events to our websocket.

    Client mode:
        If USE_PER_SPEAKER_FLUX=1 (default): NO Recall.ai STT. We receive
        only audio_separate_raw events and run our own per-speaker Flux.
        If USE_PER_SPEAKER_FLUX=0: falls back to Recall.ai STT (AssemblyAI
        or Deepgram). Matches websocket_server.py toggle.

    USE_ASSEMBLYAI (only used in standup mode and client-with-Recall-STT):
        True  → AssemblyAI Universal-3 Pro Streaming
        False → Deepgram Nova-3 with 400ms endpointing
"""

import asyncio
import os
import httpx

RECALL_REGION   = os.environ.get("RECALLAI_REGION", "ap-northeast-1")
RECALL_API_BASE = f"https://{RECALL_REGION}.recall.ai/api/v1"

# ── Per-Speaker Flux toggle (must match websocket_server.py) ────────────────
# When True + client mode, skip Recall.ai STT entirely.
USE_PER_SPEAKER_FLUX = os.environ.get("USE_PER_SPEAKER_FLUX", "1") != "0"

# ── STT PROVIDER TOGGLE (used when Recall.ai STT is active) ─────────────────
# True  = AssemblyAI Universal-3 Pro
# False = Deepgram Nova-3
USE_ASSEMBLYAI = True

SILENT_MP3_B64 = "SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4LjI5LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAACAAADkADMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzM//////////////////////////////////////////////////////////////////8AAAAATGF2YzU4LjU0AAAAAAAAAAAAAAAAJAAAAAAAAAAAkFCGaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"


class RecallBot:
    def __init__(self):
        self.api_key = os.environ["RECALLAI_API_KEY"]
        self.bot_id: str | None = None
        self.headers = {
            "Authorization": f"Token {self.api_key}",
            "Content-Type":  "application/json",
            "accept":        "application/json",
        }

    def _build_transcript_provider(self) -> dict:
        """Build the transcript.provider block.

        AssemblyAI:
            speech_model is REQUIRED (confirmed by Recall.ai support on
            Apr 22 2026 — AssemblyAI rejects requests without it with
            error_code 3006). Valid values for streaming: "universal" or
            "universal_streaming" — starting with "universal" per their
            current API docs. If this value is wrong, try "best" or
            "nano" as fallbacks.

            Turn detection tuning:
              min_turn_silence: 400ms — silence before turn COULD end
              max_turn_silence: 1280ms — silence that FORCES turn end
              vad_threshold: 0.4 — balanced sensitivity

            This should mean Sam waits up to 400ms of silence before
            finalizing, preventing interruption on natural breath pauses.

        Deepgram (fallback):
            endpointing: 400ms (up from default 150ms)
            Less accurate turn detection than Flux but much simpler.
        """
        if USE_ASSEMBLYAI:
            return {
                "assembly_ai_v3_streaming": {
                    # REQUIRED — Recall.ai's schema doesn't list this but
                    # AssemblyAI's backend rejects requests without it.
                    "speech_model": "universal",
                    # Turn detection — keeps Sam from cutting off on pauses
                    "min_turn_silence": 400,
                    "max_turn_silence": 1280,
                    "vad_threshold": 0.4,
                    # Domain vocab boost
                    "keyterms_prompt": [
                        "AnavClouds",
                        "AnavClouds Software Solutions",
                        "Salesforce",
                        "Sam",
                    ],
                }
            }
        else:
            return {
                "deepgram_streaming": {
                    "language":    "en",
                    "model":       "nova-3",
                    # 400ms endpointing: tolerate natural breath pauses
                    "endpointing": 400,
                    "keyterm": [
                        "AnavClouds",
                        "AnavClouds Software Solutions",
                        "Salesforce",
                        "Sam",
                    ],
                }
            }

    async def join(self, meeting_url: str, websocket_url: str,
                   audio_page_url: str = None, use_output_media: bool = True,
                   mode: str = "client") -> str:
        """Join a meeting. If audio_page_url provided and use_output_media=True,
        uses Output Media for streaming audio. Otherwise falls back to output_audio API.

        mode: 'standup' or 'client'. In client mode, enables Perfect Diarization
        (per-participant separate streams) for better speaker attribution during
        overlapping speech. Works with both Deepgram and AssemblyAI.
        """

        platform = "Google Meet" if "meet.google" in meeting_url else \
                   "Teams" if "teams.microsoft" in meeting_url else \
                   "Zoom" if "zoom.us" in meeting_url else "Unknown"

        # Decide STT strategy:
        #   - Standup mode → always use Recall.ai STT (AssemblyAI/Deepgram)
        #   - Client mode + USE_PER_SPEAKER_FLUX → NO Recall.ai STT, we run our own
        #   - Client mode + toggle off → fall back to Recall.ai STT
        use_recall_stt = (mode == "standup") or (not USE_PER_SPEAKER_FLUX)

        if use_recall_stt:
            stt_label = "AssemblyAI Universal-3 Pro" if USE_ASSEMBLYAI else "Deepgram Nova-3"
        else:
            stt_label = "Per-speaker Flux (own STT, no Recall.ai STT)"
        print(f"[Recall.ai] Joining {platform} meeting... (STT: {stt_label})")

        # Base realtime events — always needed
        realtime_events = [
            "participant_events.speech_on",
            "participant_events.speech_off",
            "participant_events.join",
            "participant_events.leave",
            "audio_mixed_raw.data",
            "audio_separate_raw.data",
        ]
        # Add Recall.ai STT events only if we're using Recall.ai STT
        if use_recall_stt:
            realtime_events.insert(0, "transcript.partial_data")
            realtime_events.insert(0, "transcript.data")

        # Base recording_config
        recording_config = {
            "audio_mixed_raw": {},
            "audio_separate_raw": {},
            "realtime_endpoints": [{
                "type":   "websocket",
                "url":    websocket_url,
                "events": realtime_events,
            }]
        }

        # Add transcript provider only when using Recall.ai STT
        if use_recall_stt:
            recording_config["transcript"] = {
                "provider": self._build_transcript_provider(),
            }

        payload = {
            "meeting_url": meeting_url,
            "bot_name":    "Sam",
            "recording_config": recording_config,
            "automatic_leave": {
                "everyone_left_timeout": {"timeout": 10, "activate_after": 1},
                "waiting_room_timeout": 300,
                "noone_joined_timeout": 300,
                "silence_detection": {"timeout": 600, "activate_after": 600},
                "bot_detection": {
                    "using_participant_names": {
                        "matches": [
                            "notetaker", "recorder", "otter", "fireflies",
                            "grain", "fathom", "copilot", "read.ai", "tl;dv",
                            "fellow", "assistant", "meeting bot", "ai bot"
                        ],
                        "timeout": 10,
                        "activate_after": 300
                    },
                    "using_participant_events": {
                        "timeout": 600,
                        "activate_after": 600
                    }
                }
            }
        }

        # ── Perfect Diarization (client mode + Recall.ai STT only) ─────
        # Only relevant when Recall.ai is doing STT. When USE_PER_SPEAKER_FLUX
        # is on, we get per-speaker streams via audio_separate_raw directly,
        # so this flag is unnecessary.
        if mode == "client" and use_recall_stt and "transcript" in recording_config:
            recording_config["transcript"]["diarization"] = {
                "use_separate_streams_when_available": True
            }
            print(f"[Recall.ai] 🎙️ Perfect Diarization enabled (client mode)")

        # ── Audio delivery mode ──────────────────────────────────────
        if use_output_media and audio_page_url:
            print(f"[Recall.ai] 🔊 Output Media mode: {audio_page_url}")
            payload["output_media"] = {
                "camera": {
                    "kind": "webpage",
                    "config": {"url": audio_page_url}
                }
            }
            payload["variant"] = {
                "google_meet": "web_4_core",
                "zoom": "web_4_core",
                "microsoft_teams": "web_4_core",
            }
            payload["automatic_audio_output"] = {
                "in_call_recording": {
                    "data": {"kind": "mp3", "b64_data": SILENT_MP3_B64}
                }
            }
        else:
            print(f"[Recall.ai] 🔊 Fallback mode: output_audio API")
            payload["automatic_audio_output"] = {
                "in_call_recording": {
                    "data": {"kind": "mp3", "b64_data": SILENT_MP3_B64}
                }
            }

        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                f"{RECALL_API_BASE}/bot/",
                headers=self.headers,
                json=payload,
            )
            if resp.status_code != 201:
                print(f"[Recall.ai] Error: {resp.text}")
            resp.raise_for_status()
            data = resp.json()

        self.bot_id = data["id"]
        print(f"[Recall.ai] Bot joined! ID: {self.bot_id}")
        return self.bot_id

    async def leave(self):
        if not self.bot_id:
            return
        for attempt in range(3):
            try:
                async with httpx.AsyncClient(timeout=10) as client:
                    await client.post(
                        f"{RECALL_API_BASE}/bot/{self.bot_id}/leave_call/",
                        headers=self.headers,
                    )
                print("[Recall.ai] Bot left the meeting.")
                self.bot_id = None
                return
            except Exception as e:
                if attempt < 2:
                    print(f"[Recall.ai] Leave failed (attempt {attempt+1}/3): {e}")
                    await asyncio.sleep(1)
                else:
                    print(f"[Recall.ai] Leave failed after 3 attempts: {e}")
                    self.bot_id = None

    async def get_status(self) -> dict:
        if not self.bot_id:
            return {}
        async with httpx.AsyncClient(timeout=10) as client:
            r = await client.get(
                f"{RECALL_API_BASE}/bot/{self.bot_id}/",
                headers=self.headers,
            )
            r.raise_for_status()
            return r.json()